### ISSUE TITLE
long searchterm investigation

### ISSUE THREAD

**Issue by WMDE-Fisch** [wmde/DeepCat-Gadget#13]
It seems the max GET request length on the wikipedia.org servers is 8k. The more general recommendation taking browser capabilities into account seems to be around 2k. (1)

Assuming a request length per category of approximately 11-12 ( id:123456789 ) (2). We can look for about 150-175 subcategories.

(1) https://stackoverflow.com/questions/2659952/maximum-length-of-http-get-request
(2) currently the English WP has a 8 digit page-id

**Comment by jkroll20** [comment]
That sounds about right... Given that we also support intersections, this limit will be reached quickly. 

It might be possible to change the <form> stuff from our JS to use POST. If we do that, we need to take into account that there are GET parameters already present. We'd have to test whether we can just mix these with our POST parameters.

**Comment by WMDE-Fisch** [comment]
The next problem there is, that CirrusSearch relies on the GET parameters with page links or results per page links. We could probably hack that as well to switch to onClick="submit()" adding hidden fields or something.... but that might be to much for a prototype gadget.

**Comment by jkroll20** [comment]
Ok, so these are the various limits we have to consider when trying to raise the number of subcategories searched, and how to change them.

* $wgCirrusSearchMaxIncategoryOptions, which is currently set to 100 in [CirrusSearch.php](https://gerrit.wikimedia.org/r/#/c/191622/6/CirrusSearch.php). Changing this would involve another patch to Cirrus. 
* [maxresultrows](https://github.com/wmde/catgraph-jsonp/blob/master/config.json.example#L3) limits the maximum subcategories returned by the jsonp interface per request (i.e. per deepcat: keyword invocation). I can change that as needed.
* The number of subcategories which can be handled by Cirrus and Elastic with good performance. This is a soft limit we have to figure out by testing, probably also have to talk to ops.
* GET request string length limit, server-side: about 8k characters. We can't change that unless we change to POST.
* GET request string length limit, browser-side: roughly 2k characters (~150-175 categories) according to Fisch. We can't change that unless we change to POST.

If I forgot something or got something wrong, please reply here.

**Comment by jkroll20** [comment]
It should be possible to mix a POST request with URL (GET-style) parameters. I am trying to switch the search form to POST via Javascript. Didn't get it to work yet (the request still uses GET for some reason).

**Comment by jkroll20** [comment]
Update: I have figured out how to switch to POST in the meantime. Now the next thing is that the searchterm replacement does not work with POST. 

We need some way to pass parameters from JS to the server side and back again. We could probably use a cookie, but I don't like this because it doesn't work if cookies are disabled. Other ideas?

**Comment by gbirke** [comment]
I have investigated this further and reached the same conclusion as @WMDE-Fisch - there are many changes needed that may be out of scope for a simple gadget. To illustrate, here is a description of the changes that would have to be done to the Gadget code when using POST instead of GET:

  - Add code for changing the methods of the search forms.
  - Find a mechanism for persisting the deepcat search parameters. See below for suggestions.
  - Add code to convert search-related links to hidden form submissions. Without hidden form submission the links will run into the get limit again.

#### Persisting deepcat search parameters
To replace the generated "incategory" terms on the result page, the original search terms containing "deepcat:" terms must be persisted between the search page and the result page. Same for the errors from the AJAX calls. We have at least 2 options for persistence:

  1. **Cookies/LocalStorage**: If choosing this option, the Javascript must check if cookies/LocalStorage are enabled and display a message to the user if not. Can be done in the existing hint code. LocalStorage would be better than cookies for this since the server does not need the cookie, the cookie also has size limits and would bloat the HTTP requests.
  2. **Mixing GET and POST***: The Gadget code in `substituteSearchRequest` and `addErrorMsgField` would have to be rewritten to append GET parameters (`deepCatSearch` and `deepCatError`) to the search forms actions instead of appending fields. The `WebRequest` class in the Wiki code munges GET and POST together (POST overriding GET), so mixing data sources is not a problem.

#### Convert search-related links
The search-related links are the scope links at the top of the search results  and the paging links at the bottom of the search results. They contain the full search term string which will be truncated when the link is clicked. My proposal to solve this:

Rewrite `appendToSearchLinks` and instead of just appending the deepCatSearch parameter to the href, create an onClick handler for the links that does the following steps:

1. Create a hidden form element with a POST action
2. Set the action of the form to the href of the link (minus the search param)
3. Append the deepCatSearch parameter to the action.
4. Add search field to the form. The value *could* come from the link, but to be sure it could also be set when `newSearchTerms` is generated.
5. Cancel the click event and submit the hidden form instead.

**Comment by tobijat** [comment]
This has been investigated in https://phabricator.wikimedia.org/T104444 and the switch from GET to POST is now tracked in https://phabricator.wikimedia.org/T105328

**Comment by tobijat** [comment]
Raising the limits in general in various places is now tracked in https://phabricator.wikimedia.org/T105695
